# python start_by_file.py --category gui --name KnowledgeTracker.md
# python start_by_file.py --category gui --name SmartRecipt.md
# python start_by_file.py --category gui --name FocusTime.md
# python start_by_file.py --category gui --name ExpenseCategorizer.md
# python start_by_file.py --category gui --name NoteArchiver.md
# python start_by_file.py --category gui --name RandomPasswordGenerator.md
# python start_by_file.py --category gui --name DayPlanner.md
# python start_by_file.py --category gui --name QuickTimer.md
# python start_by_file.py --category gui --name BMICalculator.md
# python start_by_file.py --category gui --name UnitConverter.md
# python start_by_file.py --category gui --name AgeCalculator.md
# python start_by_file.py --category gui --name ScienceExperimentPlanner.md
# python start_by_file.py --category gui --name TimeTracker.md
# python start_by_file.py --category gui --name TextSnippetOrganizer.md
# python start_by_file.py --category gui --name CountdownTimer.md
# python start_by_file.py --category gui --name TimeSaver.md
# python start_by_file.py --category gui --name ExpenseSplitter.md
# python start_by_file.py --category gui --name TimeConverter.md
# python start_by_file.py --category gui --name SecretNoteKeeper.md
# python start_by_file.py --category gui --name TaskTracker.md
python start_by_file.py --category game --name TicTacToe.md
# python start_by_file.py --category game --name DodgeFallingObjects.md
# python start_by_file.py --category game --name SpaceInvaders.md
python start_by_file.py --category game --name TreasureHunt.md
# python start_by_file.py --category game --name FlappyBirdClone.md
# python start_by_file.py --category game --name DriftRivals.md
# python start_by_file.py --category game --name SnakeGame.md
# python start_by_file.py --category game --name SymbolicSudoku.md
# python start_by_file.py --category game --name MazeRunner.md
# python start_by_file.py --category game --name JumppingFrog.md
python start_by_file.py --category game --name TargetShooter.md
# python start_by_file.py --category game --name GravitySpeedway.md
# python start_by_file.py --category game --name GemBlast.md
# python start_by_file.py --category game --name ColorSwapChallenge.md
# python start_by_file.py --category game --name MemoryGame.md
# python start_by_file.py --category game --name FallingObjects.md
# python start_by_file.py --category game --name SlideMaze.md
python start_by_file.py --category game --name TeamBuilder.md
# python start_by_file.py --category game --name WordGridChallenge.md
# python start_by_file.py --category game --name NumberConnect.md
# python start_by_file.py --category website --name CultureFacts.md
# python start_by_file.py --category website --name TravelRecommender.md
# python start_by_file.py --category website --name NewsReader.md
# python start_by_file.py --category website --name ShopPal.md
# python start_by_file.py --category website --name BookWormSearch.md
# python start_by_file.py --category website --name OfficeTaskFeedback.md
# python start_by_file.py --category website --name MedicalInfoTracker.md
# python start_by_file.py --category website --name SocialLearn.md
# python start_by_file.py --category website --name CulturalStoryteller.md
# python start_by_file.py --category website --name VehicleMaintenanceTracker.md
# python start_by_file.py --category website --name TravalTipper.md
# python start_by_file.py --category website --name TravalMemoryShare.md
# python start_by_file.py --category website --name QuickSearch.md
# python start_by_file.py --category website --name CulturalCalendar.md
# python start_by_file.py --category website --name TripSaver.md
# python start_by_file.py --category website --name WhishListTracker.md
# python start_by_file.py --category website --name EcoFriendlyLivingTips.md
# python start_by_file.py --category website --name MedicalTestResultTracker.md
# python start_by_file.py --category website --name SportsEquipmentInventoryTracker.md
# python start_by_file.py --category website --name SocialShare.md
# python start_by_file.py --category website --name TravelLog.md