# change to your api_key & base_url
llm_3_5:
  api_type: "openai"
  base_url: ""
  api_key: ""
  model: "gpt-3.5-turbo-16k"

llm_4o:
  api_type: "openai"
  # base url, not required.
  base_url: "https://api.chatanywhere.tech"
  # your api here
  api_key: "" 
  model: "gpt-4o-mini"
  ### gpt-4o-ca
